name: Jvav CI with Toilet
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Jvav 114514
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Grant execute permission for Toilet
      run: chmod +x gradlew
    - name: Build with Jvav Toilet
      run: ./gradlew build
    - name: Upload build feces
      uses: actions/upload-artifact@v3.1.0
      with:
        path: build/libs/*
